version: '3'

services:

  dockerize-vuejs-app:
    container_name: dockerize-vuejs-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:80'
